services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - network_app
  node:
    image: node:latest
    volumes:
      - ./:/var/www/html
      - ./node_modules:/var/www/html/node_modules
    working_dir: /var/www/html
    command: ['npm', 'run', 'dev']
    ports:
      - "5173:5173"
    networks:
      - network_app
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - network_app

networks:
  network_app:
    driver: bridge
