name: Laravel deploy

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set up environment with php and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, exif, pcntl, bcmath, gd, pdo_mysql, zip
          tools: composer

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Create file .env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Build front-end
        run: |
          npm install
          npm run build

      - name: Run tests
        env:
          DB_CONNECTION: sqlite
          APP_ENV: testing
          DB_DATABASE: testing
        run: |
          php artisan migrate --force
          php artisan test

  deploy:
    runs-on: ubuntu-24.04
    needs: laravel-tests

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /var/www/rapido-frete.carlosalexandre.com.br/deploy_workflow/script.sh /var/www/rapido-frete.carlosalexandre.com.br
